---
title: "_03_control_studies"
author: "Josefina Weinerova"
date: "2025-10-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# package loading
```{r}
# install.packages("openalexR")
if (!require(pacman)) install.packages("pacman")

pacman::p_load(
  openalexR, cowplot, tidyverse, httr, jsonlite,
  citecorp, rcrossref, purrr, dplyr, tibble, fect, furrr, future, data.table,
  panelView
)

source("R/api_cache.R")
source("R/data_prep.R")
```

#data loading
```{r}
matched_journals <- readRDS("data/matched_journals.rds")
df_meta <- readRDS("data/metadata_OpenAlex.rds")
missing_dois <- readRDS("data/missing_from_journal_matching.rds")
```

# getting control studies


```{r}
# Tidy split + normalize + dedupe
get_matches <- matched_journals %>%
  select(publication_year, issn) %>%
  tidyr::separate_rows(issn, sep = "\\s*,\\s*") %>% # split to rows
  mutate(
    year = suppressWarnings(as.integer(publication_year)),
    issn = clean_issn(issn)
  ) %>%
  distinct(year, issn, .keep_all = TRUE) %>%
  filter(!is.na(issn), !is.na(year))


range(get_matches$year)

str(get_matches)
```

# query oa_fetch in batches to get articles published in those journals based on issn and year
```{r}
options(openalexR.apikey = Sys.getenv("OA_API_KEY"))

# assumes get_matches has columns: issn (e.g., "1234-5678") and year (integer)
fetch_issn_year <- purrr::slowly(
  purrr::safely(function(issn, year) {
    message(sprintf("ISSN=%s, year=%s", issn, year))
    cached_oa_fetch(
      entity = "works",
      `primary_location.source.issn` = issn,
      publication_year = year,
      type = "article",
      per_page = 200,
      options = list(
        select = c("id", "doi", "display_name", "publication_year", "primary_location")
      ),
      cache_key = list(stage = "matched_journal_articles"),
      verbose = TRUE
    )
  }),
  rate = purrr::rate_delay(0.2)
)

results <- purrr::map2(
  get_matches$issn, get_matches$year,
  fetch_issn_year,
  .progress = TRUE
)

# keep only successful, non-empty data frames; warn on the rest
keep_df <- purrr::imap(results, function(r, i) {
  issn <- get_matches$issn[i]
  yr <- get_matches$year[i]
  if (!is.null(r$error)) {
    warning(sprintf("Failed for ISSN=%s, year=%s: %s", issn, yr, conditionMessage(r$error)))
    return(NULL)
  }
  if (is.data.frame(r$result) && nrow(r$result) > 0) r$result else NULL
})

matched_articles <- dplyr::bind_rows(keep_df) %>%
  dplyr::distinct(id, .keep_all = TRUE) %>%
  dplyr::rename(title = display_name)

length(unique(matched_articles$issn_l))
length(unique(get_matches$issn))
matched_articles
```

# get missing metadata after the first scrape

```{r}
# checking if still missing some
pairs1 <- unique(matched_articles[c("publication_year", "issn_l")])
pairs2 <- unique(matched_journals[c("publication_year", "issn")])
pairs2 <- pairs2 %>% separate(issn, into = c("issn1", "issn2"))
pairs2 <- pairs2 %>%
  mutate(issn1 = str_c(str_sub(issn1, 1, 4), "-", str_sub(issn1, 5, 8))) %>%
  mutate(issn2 = str_c(str_sub(issn2, 1, 4), "-", str_sub(issn2, 5, 8)))
# which combo of year and issn is not in the articles but is in the journals
first_pairs <- pairs1 %>%
  transmute(publication_year = publication_year, issn = issn_l)
df2_key <- pairs2 %>% mutate(.row = row_number())

has_match_rows <- df2_key %>%
  pivot_longer(c(issn1, issn2), names_to = "which", values_to = "issn") %>%
  filter(!is.na(issn), nzchar(issn)) %>%
  semi_join(first_pairs, by = c("publication_year", "issn")) %>%
  distinct(.row)

rows_not_in_first <- df2_key %>%
  anti_join(has_match_rows, by = ".row")

get <- rows_not_in_first %>%
  select(publication_year, issn1, issn2) %>%
  pivot_longer(cols = c(issn1, issn2), values_to = "issn")
get <- get %>% filter(issn != "-")

fetch_missing <- purrr::slowly(
  purrr::safely(function(issn, year) {
    cached_oa_fetch(
      entity = "works",
      `primary_location.source.issn` = issn,
      publication_year = year,
      type = "article",
      options = list(select = c("id", "doi", "display_name", "publication_year", "primary_location")),
      cache_key = list(stage = "missing_journal_articles"),
      verbose = TRUE
    )
  }),
  rate = purrr::rate_delay(0.2)
)

results_miss <- purrr::map2(
  get$issn, get$publication_year,
  fetch_missing,
  .progress = TRUE
)

out_miss <- purrr::map(results_miss, ~ .x$result) %>%
  purrr::keep(~ is.data.frame(.x) && nrow(.x) > 0) %>%
  dplyr::bind_rows() %>%
  dplyr::distinct(id, .keep_all = TRUE) %>%
  dplyr::rename(title = display_name)

#matched_articles <- dplyr::select(matched_articles, -license)
all_matched_articles <- rbind(matched_articles, out_miss)
all_matched_articles <- all_matched_articles %>% mutate(doi = stringr::str_remove(doi, regex("^https?://(dx\\.)?doi\\.org/", TRUE)))
```
#some journals are not in sjr - will query studies in them instead via source_id from OpenAlex and year
```{r}

get2 <- df_meta %>%
  filter(doi_o %in% missing_dois) %>%
  select(publication_year, issn_l, source_id, doi_o)
get2 <- unique(get2)
get2 %>% filter(is.na(source_id))
# out_miss2 <- cached_oa_fetch(
#   entity = "works",
#   `primary_location.source.issn` = get2$source_display_name, # Nature's ISSN-L (example)
#   publication_year = get2$publication_year,
#   type = "article",
#   options = list(
#     select = c("id", "doi", "display_name", "publication_year", "primary_location")
#   ),
#   cache_key = list(stage = "missing_original_articles"),
#   verbose = TRUE
# )

fetch_missing2 <- purrr::slowly(
  purrr::safely(function(source_id, year) {
    message(sprintf("journal=%s, year=%s", source_id, year))
    cached_oa_fetch(
      entity = "works",
      `primary_location.source.id` = source_id,
      publication_year = year,
      type = "article",
      options = list(select = c("id", "doi", "display_name", "publication_year", "primary_location")),
      cache_key = list(stage = "missing_journal_articles_byname"),
      verbose = TRUE
    )
  }),
  rate = purrr::rate_delay(0.2)
)

results_miss2 <- purrr::map2(
  get2$source_id, get2$publication_year,
  fetch_missing2,
  .progress = TRUE
)

out_miss2 <- purrr::map(results_miss2, ~ .x$result) %>%
  purrr::keep(~ is.data.frame(.x) && nrow(.x) > 0) %>%
  dplyr::bind_rows() %>%
  dplyr::distinct(id, .keep_all = TRUE) %>%
  dplyr::rename(title = display_name)


#out_miss2 <- out_miss2 %>% rename(title = display_name)
#out_miss2 <- dplyr::select(out_miss2, -license)
all_matched_articles <- rbind(all_matched_articles, out_miss2)
all_matched_articles <- all_matched_articles %>% mutate(doi = stringr::str_remove(doi, regex("^https?://(dx\\.)?doi\\.org/", TRUE)))

setdiff(df_meta$doi_o, all_matched_articles$doi)

```

#save ouput
```{r}
saveRDS(all_matched_articles, "data/all_matched_articles.rds")
saveRDS(get2, "data/missing_from_matched_journals.rds")
```
